-- CreateTable
CREATE TABLE "Country" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "iso" TEXT NOT NULL,
    "iso3" TEXT,
    "name" TEXT NOT NULL,
    "niceName" TEXT NOT NULL
);
